export * from './auth.service';
import { AuthService } from './auth.service';
export * from './facility.service';
import { FacilityService } from './facility.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './production.service';
import { ProductionService } from './production.service';
export * from './purchase.service';
import { PurchaseService } from './purchase.service';
export * from './stockBalanceView.service';
import { StockBalanceViewService } from './stockBalanceView.service';
export * from './supplier.service';
import { SupplierService } from './supplier.service';
export * from './supply.service';
import { SupplyService } from './supply.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuthService, FacilityService, PaymentService, ProductService, ProductionService, PurchaseService, StockBalanceViewService, SupplierService, SupplyService, UserService];
