/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { ProblemDetails } from '../model/problemDetails';
// @ts-ignore
import { ProductTypeEnum } from '../model/productTypeEnum';
// @ts-ignore
import { StockBalanceViewDtoPagedListDtoResult } from '../model/stockBalanceViewDtoPagedListDtoResult';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';


export interface ApiStockBalanceViewGetRequestParams {
    facilityId?: number;
    productId?: number;
    productType?: ProductTypeEnum;
    balanceDate?: string;
    pageNumber?: number;
    pageSize?: number;
    searchTerm?: string;
    sortBy?: string;
    sortDescending?: boolean;
}


@Injectable({
  providedIn: 'root'
})
export class StockBalanceViewService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @endpoint get /api/StockBalanceView
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiStockBalanceViewGet(requestParameters?: ApiStockBalanceViewGetRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<StockBalanceViewDtoPagedListDtoResult>;
    public apiStockBalanceViewGet(requestParameters?: ApiStockBalanceViewGetRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpResponse<StockBalanceViewDtoPagedListDtoResult>>;
    public apiStockBalanceViewGet(requestParameters?: ApiStockBalanceViewGetRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<HttpEvent<StockBalanceViewDtoPagedListDtoResult>>;
    public apiStockBalanceViewGet(requestParameters?: ApiStockBalanceViewGetRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json', context?: HttpContext}): Observable<any> {
        const facilityId = requestParameters?.facilityId;
        const productId = requestParameters?.productId;
        const productType = requestParameters?.productType;
        const balanceDate = requestParameters?.balanceDate;
        const pageNumber = requestParameters?.pageNumber;
        const pageSize = requestParameters?.pageSize;
        const searchTerm = requestParameters?.searchTerm;
        const sortBy = requestParameters?.sortBy;
        const sortDescending = requestParameters?.sortDescending;

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>facilityId, 'FacilityId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>productId, 'ProductId');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>productType, 'ProductType');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>balanceDate, 'BalanceDate');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageNumber, 'PageNumber');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>pageSize, 'PageSize');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>searchTerm, 'SearchTerm');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sortBy, 'SortBy');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sortDescending, 'SortDescending');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'text/plain',
            'application/json',
            'text/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/StockBalanceView`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<StockBalanceViewDtoPagedListDtoResult>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
