/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserCommand { 
    username?: string | null;
    email?: string | null;
    password?: string | null;
    firstName?: string | null;
    lastName?: string | null;
}

