/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductTypeEnum } from './productTypeEnum';
import { UnitOfMeasureEnum } from './unitOfMeasureEnum';
import { ProductSpecificationData } from './productSpecificationData';


export interface CreateOrUpdateProductCommand { 
    id?: number | null;
    name?: string | null;
    productType?: ProductTypeEnum;
    unitOfMeasure?: UnitOfMeasureEnum;
    specification?: ProductSpecificationData;
}
export namespace CreateOrUpdateProductCommand {
}


