/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateOrUpdatePurchaseCommand { 
    id?: string | null;
    supplierId?: number;
    facilityId?: number;
    productId?: number;
    amount?: number;
    quantity?: number;
}

