/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentMethodEnum } from './paymentMethodEnum';


export interface CreateOrUpdatePaymentCommand { 
    id?: string | null;
    purchaseId?: string;
    amount?: number;
    paymentMethod?: PaymentMethodEnum;
}
export namespace CreateOrUpdatePaymentCommand {
}


