/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentDto } from './paymentDto';


export interface PaymentDtoResult { 
    isSuccess?: boolean;
    errors?: Array<string> | null;
    readonly errorMessage?: string | null;
    data?: PaymentDto;
}

