/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductTypeEnum } from './productTypeEnum';
import { UnitOfMeasureEnum } from './unitOfMeasureEnum';


export interface ProductSpecificationItemDto { 
    id?: number;
    productSpecificationId?: number;
    productId?: number;
    productName?: string | null;
    productType?: ProductTypeEnum;
    quantity?: number;
    unitOfMeasure?: UnitOfMeasureEnum;
}
export namespace ProductSpecificationItemDto {
}


