/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductSpecificationItemDto } from './productSpecificationItemDto';


export interface ProductSpecificationDto { 
    id?: number;
    productId?: number;
    version?: string | null;
    isActive?: boolean;
    dateCreated?: string;
    items?: Array<ProductSpecificationItemDto> | null;
}

