/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpecificationItem } from './specificationItem';


export interface ProductSpecificationData { 
    version?: string | null;
    setAsActive?: boolean;
    items?: Array<SpecificationItem> | null;
}

