/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PurchaseDtoPagedListDto } from './purchaseDtoPagedListDto';


export interface PurchaseDtoPagedListDtoResult { 
    isSuccess?: boolean;
    errors?: Array<string> | null;
    readonly errorMessage?: string | null;
    data?: PurchaseDtoPagedListDto;
}

