/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductTypeEnum } from './productTypeEnum';
import { UnitOfMeasureEnum } from './unitOfMeasureEnum';


export interface StockBalanceViewDto { 
    facilityName: string;
    productName: string;
    productType: ProductTypeEnum;
    unitOfMeasure: UnitOfMeasureEnum;
    startBalance?: number;
    incomeBalance?: number;
    outcomeBalance?: number;
    finishBalance?: number;
    balanceDate: string;
}
export namespace StockBalanceViewDto {
}


