/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StockBalanceViewDtoPagedListDto } from './stockBalanceViewDtoPagedListDto';


export interface StockBalanceViewDtoPagedListDtoResult { 
    isSuccess?: boolean;
    errors?: Array<string> | null;
    readonly errorMessage?: string | null;
    data?: StockBalanceViewDtoPagedListDto;
}

