/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StockMovementDto { 
    facilityName?: string | null;
    productName?: string | null;
    quantity?: number;
    dateCreated?: string;
}

