/**
 * CubArt API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StockMovementDto } from './stockMovementDto';


export interface SupplyDto { 
    stockMovementList?: Array<StockMovementDto> | null;
    id: string;
    purchaseId: string;
    quantity: number;
    dateCreated: string;
}

